name: Check PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  quick-checks:
    name: Quick checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup test workspace
        uses: ./.github/actions/setup-test-workspace

      - name: Run checks and tests
        run: pnpm exec turbo run check-format check-types lint test:unit test:storybook

      - name: Upload unit test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-artifacts
          path: |
            apps/*/test-artifacts/unit
            packages/*/test-artifacts/unit
          retention-days: 7

      - name: Upload storybook test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-test-artifacts
          path: |
            apps/*/test-artifacts/storybook
            packages/*/test-artifacts/storybook
          retention-days: 7

  e2e-tests:
    name: E2E tests (on demand)
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'e2e') }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup test workspace
        uses: ./.github/actions/setup-test-workspace

      - name: Run E2E tests
        run: pnpm exec turbo run test:e2e

      - name: Upload e2e test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-artifacts
          path: |
            apps/*/test-artifacts/e2e
            packages/*/test-artifacts/e2e
          retention-days: 7
